import "@src/styles/global.scss";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Ade Prianto</title>
        <meta name="description" content="This is website of Ade Prianto" />
        <meta name="author" content="Ade Prianto" />
        <meta name="keywords" content="Ade Prianto, Ade, Prianto" />
        <link rel="icon" href="/assets/icons/favicon.png" />
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
